### ISSUE TITLE
add reference to other translations in the readme

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/measuringoutcome-cht#7]
See readme for spanish, english or dutch for style and to copy references :-)

**Comment by sjoerdly** [comment]
This is how it should/could be added, in other readme's it is before the license heading, after the releases heading.

Copy paste the below markdown and translate appropriate parts to chinese pls 

```
## Other languages

- [Measure Outcomes](https://github.com/ScrumFacilitators/measuringoutcome-en/releases/latest) (English) / Inglés (original)
- [Uitkomsten Meten](https://github.com/ScrumFacilitators/measuringoutcome-nl/releases/latest) (Nederlands) / Translation in dutch
- [Medición del Resultado](https://github.com/ScrumFacilitators/measuringoutcome-es/releases/latest) (Español) / Translation in spanish
```

The part for each reference after the slash (/) should be chinese too. The idea is to have the translation linked in the translated language, with the chinese short description after the slash.

Please do ask in case of questions!

**Comment by ctonylee** [comment]
Done, added the following into README.md

```
## 其他的語言

- [Measure Outcomes](https://github.com/ScrumFacilitators/measuringoutcome-en/releases/latest) (English) / 英文 (original)
- [Uitkomsten Meten](https://github.com/ScrumFacilitators/measuringoutcome-nl/releases/latest) (Nederlands) / 荷(蘭)文
- [Medición del Resultado](https://github.com/ScrumFacilitators/measuringoutcome-es/releases/latest) (Español) / 西班牙文```
