### ISSUE TITLE
Translate facilitator instructions

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/measuringoutcome-cht#8]
Just noticed that facilitator instructions are still english. For other translations, I figured these were the most important part to be translated... 

Is there a specific reason why this isn't done here @ctonylee & @cheehonghsia ?

**Comment by ctonylee** [comment]
Hi @sjoerdly,  I didn't have time to work on it back then and now working on translating the instructions now.

Few questions about the instructions: 
> 1.Step 1: Invite the group(s) to discuss and put the KVMs under the correct KVA.

Q1-1) In Step 1, does `Invite the group(s)` mean each group work on their own with  Green and Purple cards and there is no communication between groups? 
Q1-2) In Step 2, what does `put the KVMs under the correct KVA` mean when in Step 2, it has a statement explicitly stated `Make sure by the end of this round, the KVM cards are under the correct KVA.`.  Is it correct to assume in Step 1, the teams are to `put the KVMs under a **corresponding** KVA `, which may or may not be correct?

> Step 2: Invite both groups to discuss their results and adapt their cards. Make sure by the end of this round, the KVM cards are under the correct KVA.

Q2-1) My guess is the Scrum Facilitator will step in on Step-2 and guiding everyone to map the KVM cards to the correct KVA. In other words, I am assuming in Step-1  the Scrum Facilitator and each group doesn't communicate beyond their group. 

> Step 3: Invite the participants to individually look at the KVMs and select one KVM that caught their attention. (A non-EBM KVM may also be chosen at this point)

Q3-1) To confirm on the instruction, the instruction is stating that the participants can choose a metric from their experience that is non-EBM KVM, correct?

**Comment by ctonylee** [comment]
Q1-1) about Step 1 : updated instruction to ask each team to discuss cards among themselves   
Q1-2) about Step 1: updated instruction to describe "mapping KVMs to corresponding KVAs" instead of using the term "correct" i Chinese  
Q2-1) updated instruction in Step 1: that the group will talk among themselves instead of across the teams  
Q3-1) translated statement staging  allow choosing non-EBM KVMs

**Comment by sjoerdly** [comment]
Hey @ctonylee I did not have the chance to comment until now, but you are correct in your assumptions around the facilitation. If you have any additional ideas or suggestions for the instructions that would improve clarity in other languages too, let us know!

Tagging @cheehonghsia as he is the originator of this game so he can confirm or update our interpretation of the facilitation. :-)

**Comment by cheehonghsia** [comment]
@ctonylee I believe we had a quick chat about your comments and I agree that we can definitely elaborate the 'how to facilitate the game' a bit more. Will include your comment in your next release.

**Comment by ctonylee** [comment]
Thanks @sjoerdly  and @cheehonghsia  for the comments！   
And yes, the update is based on the clarification in discussion with @cheehonghsia  verbal during a zoom call when teaching others about how to run the workshop.   
  
Lessons learned: I will add more background note in the comments in the future! 🙏
